baseURL = 'https://purchase.aspose.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'pricing'
draft = "false"

[module]
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content'
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  

[params]
    url = "https://purchase-api.dynabic.com/v1.2/productFamily/site-aspose?isArchived=&pageNumber=&pageSize=&applyDisplayOrder=true&includeProducts=false&enabledPPPOn=&clientkey=a&signature=jc_xWmdMtA-nMA2Bgp9vuEV0Kn0"


defaultContentLanguage = 'en'
[languages]
  [languages.en]
    title = "Pricing information"
    languageName = "English"
    weight = 1
